[package]
name = "config_app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ecu_diagnostics={git="https://github.com/rnd-ash/ecu_diagnostics"}
eframe = { version = "*", default-features = false, features = ["default_fonts", "egui_glow"] }
egui="0.15.0"
image = "0.23.12"
serialport = "4.0.1" # For manual USB connection
