[package]
name = "config_app"
version = "0.1.0"
edition = "2021"
resolver = "2"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ecu_diagnostics="0.90.33"
#egui="0.15.0"
image = "0.24.1"
#serialport = {git = "https://github.com/rnd-ash/serialport-rs"} # For manual USB connection
serial-rs = {git="https://github.com/rnd-ash/serial-rs"}
nfd="0.0.4"
egui_wgpu_backend = "0.17"
egui_winit_platform = "0.14.0"
pollster = "0.2.5"
egui = "0.17.0"
epi = "0.17.0"
wgpu = "0.12"
winit = "0.26.1"
egui-winit = "0.17.0"
modular-bitfield = "0.11.2"
static_assertions = "1.1.0"